### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Lorraine97** [Lorraine97/DSCI_532_Dash#1]
Name of App: Dash Demo for climdash
Link to Dashboard: [onrender link](https://dsci532-xinrulu-dash-demo.onrender.com/)
Link to Repo: https://github.com/Lorraine97/DSCI_532_Dash

Dashboard: 
<img width="1444" alt="Screenshot 2023-03-21 at 23 28 28" src="https://user-images.githubusercontent.com/40663725/226820046-cfaeb254-47ff-41ce-ae1b-0039bf8d3599.png">

**Comment by kellywujy** [comment]
Nice layout and color scheme chosen for the dashboard! Here are some suggestions:
- I suggest change the title of the dashboard to a more descriptive title, instead of Dash demo.
- For the temperature heatmap, the color encoding would change based on the range of value corresponding to each year. From user's perception viewpoint, this means the same color correspond to different numerical value in different year. I suggest forcing the color scale to be consistent throughout all years to allow easier comparison.
-
